age= input("enter your current age:")
ages= int(age)
days= round((365*90)-(365*ages))
weeks= round((52*90)-(52*ages))
months= round((12*90)-(12*ages))
print(f"you have {days} days,{weeks} weeks and {months} months left")
